@GuidedProject.ApiApp_HostAddress = http://localhost:5153

GET {{GuidedProject.ApiApp_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GuidedProject.ApiApp_HostAddress}}/api/chat/complete
Accept: application/json
Content-Type: application/json

{
  "prompt": "who are you?"
}

###
